version : '3.1'

# MongoDB, Postgres, Redis, Elasticsearch, Kibana, Mysql, Postgres
#define all images from where to 'generate or instantiate' a container
services:
  #container name
  mongo:
    #from image
    image: mongo:latest
    #on crash restart automatically
    restart: always
    #Define environment variable
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      #port mapping, forward port from container to host machine
      #it means every time there's a connection to that port on host machine it'll be forwarded to the container port
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # AMQP protocol
      - '15672:15672' #WEB UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}